ICA/ica.website/Controllers/WebNewsController.cs
using ica.website.Domain;
using ica.website.Infrastructure;
using ica.website.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using System.Web.Mvc;

namespace ica.website.Controllers
{
    [Authorize(Roles = "Web Maintenance")]
    public class WebNewsController : AppFrameController
    {
        private readonly IBaseOperations _context;
        private readonly ICurrentUser _currentUser;
        public WebNewsController(IBaseOperations context, ICurrentUser currentUser)
        {
            _context = context;
            _currentUser = currentUser;
        }
        public ActionResult Index(long? languageId = 1)
        {
            ViewBag.selected = languageId;
            var modal = _context.Get<WebNews>(d => d.WebNewsType.LanguageId == languageId).OrderByDescending(d => d.Id).Include(d => d.WebNewsType).ToList();
            return View(modal);
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult Index(FormCollection input)
        {
            var IdArray = input.GetValues("item.Id");
            var NameArray = input.GetValues("item.Name");
            var ImageArray = input.GetValues("item.Image");
            var ContentArray = input.GetValues("item.Content");
            var DateArray = input.GetValues("item.Date");
            var ShortDescriptionArray = input.GetValues("item.ShortDescription");
            
            var WebNewsTypeIdArray = input.GetValues("item.WebNewsTypeId");

            long lanaguageId = 1;
            var LanguageIdArray = input.GetValues("item.LanguageId");
            if (LanguageIdArray.Count() > 0)
            {
                lanaguageId = Convert.ToInt64(LanguageIdArray[0]);
            }

            for (int i = 0; i < IdArray.Count(); i++)
            {
                var Id = Convert.ToInt64(IdArray[i]);
                var entity = _context.FindDetail<WebNews>(Id);
                entity.Name = NameArray[i];
                entity.WebNewsTypeId = Convert.ToInt64(WebNewsTypeIdArray[i]);
                entity.Date= Convert.ToDateTime(DateArray[i]);
                var content = ContentArray[i];
                entity.Image = _context.GetImage(content, "news");
                entity.ShortDescription = ShortDescriptionArray[i];
                entity.Content = content;
                entity.UpdatedDate = DateTime.Now;
            }
            _context.SaveChange();
            return RedirectToAction<WebNewsController>(d => d.Index(lanaguageId));
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult Add(WebNews input)
        {
            input.Image = _context.GetImage(input.Content, "news");
            input.UpdatedDate = DateTime.Now;
            _context.AddOneEntity<WebNews>(input);
            return RedirectToAction<WebNewsController>(d => d.Index(input.LanguageId));
        }
        public JsonResult _Delete(long id)
        {
            try
            {
                _context.DeleteOneEntity<WebNews>(id);
                return Json("success", JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json("fail", JsonRequestBehavior.AllowGet);
            }
        }
    }
}

ICA/ica.website/Views/WebNews/Index.cshtml
@using ica.website.Models;
@using ica.website.Domain;
@using ica.website.Infrastructure
@model IEnumerable<WebNews>
<div class="container">
    <div class="row">
        <div class="col-md-2">
            @Html.Partial("_WebButtons", "News")
        </div>
        <div class="col-md-10">
            <div class="row" style="margin-top:20px;margin-bottom:20px;">
                @using (Html.BeginForm("Index", "WebNews", FormMethod.Post, new { onsubmit = "saveAll()" }))
            {
                    <div class="col-md-8 text-right">
                        @Html.Partial("_LanguageDropDownList")
                    </div>
                    <div class="col-md-4">
                        <div style="margin-left:20px;margin-right:20px;">
                            <input type="submit" value="Save all" class="btn btn-primary" />
                            <input type="button" value="Add" class="btn btn-primary" data-toggle="modal" data-target="#modalAdd" />
                        </div>
                    </div>
                    <div class="col-md-12" style="margin-top:20px;">
                        <table class="table">
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Name)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.ShortDescription)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Date)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.WebNewsTypeId)
                                </th>
                                <th>
                                    Action
                                </th>
                            </tr>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.HiddenFor(modelItem => item.Id)
                                        @Html.HiddenFor(modelItem => item.LanguageId)
                                        @Html.TextBoxFor(modelItem => item.Name, new { @class = "form-control" })
                                    </td>
                                    <td>
                                        @Html.EditorFor(modelItem => item.ShortDescription, new { @class = "form-control" })
                                    </td>
                                    <td>
                                        @Html.EditorFor(modelItem => item.Date, new { @class = "form-control" })
                                    </td>
                                    <td>
                                        @Html.EditorFor(modelItem => item.WebNewsTypeId, new { @class = "form-control" })
                                    </td>
                                    <td>
                                        <a href="#" data-toggle="modal" data-target=@Html.Raw("#ModalDelete" + item.Id)>Delete</a>
                                        @Html.Partial("_Delete", item)
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="6">
                                        @Html.TextBoxFor(modelItem => item.Content, new { @class = "form-control", id = item.Id + "content" })
                                    </td>
                                </tr>
                            }
                        </table>
                    </div>
                }
            </div>
        </div>
    </div>
    </div>
    @Html.Partial("_Add", new WebNews() { LanguageId = (long)ViewBag.selected })
    @section scripts{
        <script>
            $(function () {
                @foreach (var item in Model)
            {
                var summer = "$('#"+item.Id+"content').summernote({height: 200,minHeight: 200,maxHeight: null,    });$('#"+item.Id+"content').code($('#"+item.Id+"content').val());";
                @Html.Raw(summer)
            }
            })
            function droplistOnchanged(e) {
                var id = $(e).val();
                link = "/WebNews/Index?languageId=" + id;
                window.location.href = link;
            }
            function saveAll() {
                @foreach (var item in Model)
                {
                    var summer = "$('#"+item.Id+"content').val($('#"+item.Id+"content').code());";
                    @Html.Raw(summer)
                }
            }
        </script>
    }

ICA/ica.website/Views/WebNews/_Add.cshtml
@using ica.website.Domain;
@model WebNews
<div class="modal fade" id="modalAdd">
    <table style="height:100%;width:100%">
        <tr>
            <td valign="middle">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h3 class="modal-title" id="myModalLabel">Add</h3>
                        </div>
                        @using (Html.BeginForm("Add", "WebNews", FormMethod.Post, new { onclick = "setAddContent()" }))
                            {
                            <div class="modal-body">
                                @Html.AntiForgeryToken()
                                @Html.HiddenFor(d => d.LanguageId)
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-horizontal">
                                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                            <div class="form-group">
                                                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                                <div class="col-md-10">
                                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                                                <div class="col-md-10">
                                                    @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                @Html.LabelFor(model => model.WebNewsTypeId, htmlAttributes: new { @class = "control-label col-md-2" })
                                                <div class="col-md-10">
                                                    @Html.EditorFor(model => model.WebNewsTypeId, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.WebNewsTypeId, "", new { @class = "text-danger" })
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-12 pull-left" })
                                            <div class="col-md-12">
                                                @Html.TextBoxFor(model => model.Content, new { @class = "form-control", id = "AddContent" })
                                                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <img class="pull-left" src="/Images/Busy.gif" id="addEventBusy" style="display: none" />
                                <label class="pull-left" id="addEventMessage"></label>
                                <button type="submit" class="btn btn-primary">Confirm</button>
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            </div>
                        }
                    </div>
                </div>
            </td>
        </tr>
    </table>
</div><!-- /.modal -->
<script type="text/javascript">
    $(function () {
        $('#AddContent').summernote({
            height: 200,                 // set editor height
            minHeight: 200,             // set minimum height of editor
            maxHeight: null,             // set maximum height of editor
        });
    })
    function setAddContent() {
        var des = $('#AddContent').code();
        $('#AddContent').val(des);
    }
</script>

ICA/ica.website/Views/WebNews/_Delete.cshtml
@using ica.website.Domain;
@model WebNews
<div class="modal fade" id=@Html.Raw("ModalDelete" + Model.Id) tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Are you sure to delete ?</h4>
            </div>
            <div class="modal-body">
                @Model.Name
            </div>
            <div class="modal-footer">
                <button type="button" data-id=@Model.Id onclick="Delete(this)" class="btn btn-primary">Confirm</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

    <script>
        function Delete(e) {
            var id = $(e).attr("data-id");
            var requrl = "/WebNews/_Delete/" + id;
            $.ajax({
                type: "POST",
                dataType: 'json',
                cashe: false,
                url: requrl,
                success: function (data) {
                    //alert(data);
                    if (data == "fail") {
                        alert("Failed to change data, please try later.");
                        return;
                    }
                    $("#ModalDelete" + id).modal('hide');
                    //$("#item" + id).hide();
                    var culumn = $("#ModalDelete" + id).parent().parent();
                    var content = culumn.next();
                    culumn.hide();
                    content.hide();
                },
                error: function (failure) {
                    alert(failure.responseText);
                }
            });
        }
    </script>