ICA/ica.website/Controllers/WebCarouselController.cs
using ica.website.Domain;
using ica.website.Infrastructure;
using ica.website.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
namespace ica.website.Controllers
{
    [Authorize(Roles = "Web Maintenance")]
    public class WebCarouselController : AppFrameController
    {
        private readonly IBaseOperations _context;
        private readonly ICurrentUser _currentUser;
        public WebCarouselController(IBaseOperations context, ICurrentUser currentUser)
        {
            _context = context;
            _currentUser = currentUser;
        }
        public ActionResult Index(Int64 languageId = 1)
        {
            ViewBag.selected = languageId;
            return View(_context.Get<WebCarousel>(d => d.LanguageId == languageId));
        }

        [HttpPost ValidateInput(false)]
        public ActionResult Index(FormCollection input)
        {
            var IdArray = input.GetValues("item.Id");
            var WordsArray = input.GetValues("item.Words");
            var BackgroudImageArray = input.GetValues("item.BackgroudImage");
            var IndicateHeaderArray = input.GetValues("item.IndicateHeader");
            var IndicateWordsArray = input.GetValues("item.IndicateWords");
            var OrderArray = input.GetValues("item.Order");
            //var IssueArray = input.GetValues("item.Issue");
            var ContentArray = input.GetValues("item.Content");
            long lanaguageId = 1;
            for (int i = 0; i < IdArray.Count(); i++)
            {
                var Id = Convert.ToInt64(IdArray[i]);
                var entity = _context.FindDetail<WebCarousel>(Id);
                lanaguageId = entity.LanguageId;
                entity.Words = WordsArray[i];
                entity.Content = ContentArray[i];
                entity.BackgroudImage = BackgroudImageArray[i];
                entity.Order = int.Parse(OrderArray[i]);
                entity.UpdatedDate = DateTime.Now;
                entity.IndicateHeader = IndicateHeaderArray[i];
                entity.IndicateWords = IndicateWordsArray[i];
                //entity.Issue = bool.Parse(IssueArray[i]);
            }
            _context.SaveChange();
            return RedirectToAction<WebCarouselController>(d => d.Index(lanaguageId));
        }
       
        public ActionResult UploadImage(HttpPostedFileBase file,FormCollection form)
        {
            var alumniId = form.GetValues("alumniId")[0];
            string pic = "";
            if (file != null)
            {
                var fileName = Path.GetFileName(file.FileName);
                var ext = fileName.Substring(fileName.IndexOf(".") + 1).ToLower();
                if (ext != "gif" && ext == "png" && ext == "jpg" && ext == "bmp")
                {
                    return Json("Sorry, you can only upload gif,png,jpg or bmp file.", JsonRequestBehavior.AllowGet);
                }
                if (file.ContentLength > 200000)//200k
                {
                    return Json("Sorry, your logo file size can not be bigger than 200k. Please upload proper size file.", JsonRequestBehavior.AllowGet);
                }
                pic = Guid.NewGuid().ToString() + "." + ext;
                string path = System.IO.Path.Combine(Server.MapPath("/images/Alumni/"), pic);
                // file is uploaded
                file.SaveAs(path);
                _context.FindDetail<ApplicationUser>(alumniId).HeaderImage = "/images/Alumni/" + pic;
                _context.SaveChange();
                return Json("alert('Seccussfull.')", JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json("alert('Please select your logo file.')", JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult Add(WebCarousel input)
        {
            input.UpdatedDate = DateTime.Now;
            _context.AddOneEntity<WebCarousel>(input);
            return RedirectToAction<WebCarouselController>(d => d.Index(input.LanguageId));
        }
        public JsonResult _Delete(long id)
        {
            try
            {
                _context.DeleteOneEntity<WebCarousel>(id);
                return Json("success", JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json("fail", JsonRequestBehavior.AllowGet);
            }
        }
    }
}

ICA/ica.website/Views/WebCarousel/Index.cshtml
@using ica.website.Models;
@using ica.website.Domain;
@using ica.website.Infrastructure
@model IEnumerable<WebCarousel>
<link href="~/Content/jquery.fileupload-ui.css" rel="stylesheet" />
<script src="~/Scripts/jquery-ui-1.10.4.js"></script>
<script src="~/Scripts/jquery.fileupload.js"></script>
<div class="container">
    <div class="row">
        <div class="col-md-2">
            @Html.Partial("_WebButtons", "Carousel")
        </div>
        <div class="col-md-10">
            <div class="row" style="margin-top:20px;margin-bottom:20px;">
                @using (Html.BeginForm("Index", "WebCarousel", FormMethod.Post, new { onsubmit = "saveAll()" }))
            {
            <div class="col-md-8 text-right">
                @Html.Partial("_LanguageDropDownList")
            </div>
            <div class="col-md-4">
                <div style="margin-left:20px;margin-right:20px;">
                    <input type="submit" value="Save all" class="btn btn-primary" />
                    <input type="button" value="Add" class="btn btn-primary" data-toggle="modal" data-target="#modalAdd" />
                </div>
            </div>
            <div class="col-md-12" style="margin-top:20px;">
                <table class="table">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Words)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.BackgroudImage)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.IndicateHeader)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.IndicateWords)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Order)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Issue)
                        </th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.HiddenFor(modelItem => item.Id)
                                @Html.TextBoxFor(modelItem => item.Words, new { @class = "form-control" })
                            </td>
                            <td>
                                @Html.EditorFor(modelItem => item.BackgroudImage, new { @class = "form-control" })
                            </td>
                            <td>
                                @Html.TextBoxFor(modelItem => item.IndicateHeader, new { @class = "form-control" })
                            </td>
                            <td>
                                @Html.TextBoxFor(modelItem => item.IndicateWords, new { @class = "form-control" })
                            </td>
                            <td>
                                @Html.TextBoxFor(modelItem => item.Order, new { @class = "form-control", style = "width:60px;", type = "number" })
                            </td>
                            <td>
                                <a href="#" data-toggle="modal" data-target=@Html.Raw("#ModalDelete" + item.Id)>Delete</a>
                                @Html.Partial("_Delete", item)
                            </td>
                        </tr>
                        <tr>
                            <td colspan="6">
                                @Html.TextBoxFor(modelItem => item.Content, new { @class = "form-control", id = item.Id + "content" })
                            </td>
                        </tr>
                    }
                </table>
            </div>
                        }
            </div>

        </div>
    </div>
    </div>
    @Html.Partial("_Add", new WebCarousel() { LanguageId = (long)ViewBag.selected })
    @*@Html.Partial("_Add", new WebCarousel())*@
    @section scripts{
        <script>
            $(function () {
                @foreach (var item in Model)
            {
                var summer = "$('#"+item.Id+"content').summernote({height: 200,minHeight: 200,maxHeight: null,    });$('#"+item.Id+"content').code($('#"+item.Id+"content').val());";
                @Html.Raw(summer)
            }
                $('.UploadImage').fileupload({
                    dataType: 'json',
                    add: function (e, data) {
                        $("#busy").css("display", "block");
                        data.submit();
                    },
                    done: function (e, data) {
                        $("#busy").css("display", "none");
                    },
                    url: '/WebCarousel/UploadImage',
                    success: function (data) {
                        data;
                        if (data == "done") {
                            showMessage("Normal", "Successfully import data.");
                            //window.location.reload();
                        } else {
                            alert("please contact admin.");
                            showMessage("Failed", "Please check your import data or contact your administrator.");
                        }
                    },
                    error: function (failure) {
                        alert(failure.responseText);
                    }
                });
            })
            function saveAll() {
                $("tr[style*='display: none']").remove();
                @foreach (var item in Model)
                {
                    var summer = "$('#"+item.Id+"content').val($('#"+item.Id+"content').code());";
                    @Html.Raw(summer)
                }
            }
            
            function droplistOnchanged(e) {
                var id = $(e).val(); //HubRateRegionQuoteType
                link = "/WebCarousel/Index?languageId=" + id;
                window.location.href = link;
            }
        </script>
    }

ICA/ica.website/Views/WebCarousel/_Add.cshtml
@using ica.website.Domain;
@model WebCarousel
<div class="modal fade" id="modalAdd">
    <table style="height:100%;width:100%">
        <tr>
            <td valign="middle">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h3 class="modal-title" id="myModalLabel">Add</h3>
                        </div>
                        @using (Html.BeginForm("Add", "WebCarousel", FormMethod.Post, null))
                        {
                            @Html.AntiForgeryToken()
                            @Html.HiddenFor(d=>d.LanguageId)
                            <div class="modal-body">
                                <div class="form-horizontal">
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Words, htmlAttributes: new { @class = "control-label col-md-4" })
                                        <div class="col-md-8">
                                            @Html.EditorFor(model => model.Words, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.Words, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.BackgroudImage, htmlAttributes: new { @class = "control-label col-md-4" })
                                        <div class="col-md-8">
                                            @Html.EditorFor(model => model.BackgroudImage, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.BackgroudImage, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-4" })
                                        <div class="col-md-8">
                                            @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.IndicateHeader, htmlAttributes: new { @class = "control-label col-md-4" })
                                        <div class="col-md-8">
                                            @Html.EditorFor(model => model.IndicateHeader, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.IndicateHeader, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.IndicateWords, htmlAttributes: new { @class = "control-label col-md-4" })
                                        <div class="col-md-8">
                                            @Html.EditorFor(model => model.IndicateWords, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.IndicateWords, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Order, htmlAttributes: new { @class = "control-label col-md-4" })
                                        <div class="col-md-8">
                                            @Html.EditorFor(model => model.Order, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.Order, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Issue, htmlAttributes: new { @class = "control-label col-md-4" })
                                        <div class="col-md-8">
                                            <div class="checkbox">
                                                @Html.EditorFor(model => model.Issue)
                                                @Html.ValidationMessageFor(model => model.Issue, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <img class="pull-left" src="/Images/Busy.gif" id="addEventBusy" style="display: none" />
                                <label class="pull-left" id="addEventMessage"></label>
                                <button type="submit" class="btn btn-primary">Confirm</button>
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            </div>
                        }
                    </div>
                </div>
            </td>
        </tr>
    </table>
</div><!-- /.modal -->

ICA/ica.website/Views/WebCarousel/_Delete.cshtml
@using ica.website.Domain;
@model WebCarousel
<div class="modal fade" id=@Html.Raw("ModalDelete" + Model.Id) tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Are you sure to delete ?</h4>
            </div>
            <div class="modal-body">
                @Html.Raw(Model.IndicateHeader)
            </div>
            <div class="modal-footer">
                <button type="button" data-id=@Model.Id onclick="Delete(this)" class="btn btn-primary">Confirm</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

    <script>
        function Delete(e) {
            var id = $(e).attr("data-id");
            var requrl = "/WebCarousel/_Delete/" + id;
            $.ajax({
                type: "POST",
                dataType: 'json',
                cashe: false,
                url: requrl,
                success: function (data) {
                    //alert(data);
                    if (data == "fail") {
                        alert("Failed to change data, please try later.");
                        return;
                    }
                    $("#ModalDelete" + id).modal('hide');
                    //$("#item" + id).hide();
                    var row = $("#ModalDelete" + id).parent().parent();
                    var content = row.next();
                    row.hide();
                    content.hide();
                },
                error: function (failure) {
                    alert(failure.responseText);
                }
            });
        }
    </script>